### ISSUE TITLE
Testing OSRM with modified profiles

### ISSUE THREAD

**Issue by RSA77** [Project-OSRM/osrm-profiles-contrib#8]
Hi,

I need to test a solution proposed in the issue "#656" of osrm-backend module, titled "How can I avoid highways or tolls".
For this i need to:
- modify car.lua profile after deleing toll_booth information, 
- re-extract osm graph and,
- re-run the osrm-backend.

Is it possible to make two "opposite profiles" cohabit together with the same osrm-backend and if yes what is the safest way to do it ?
An example of two opposite profiles: 
- car.lua 
- carTollfree.lua (where toll_booth information has been deleted.

Thanks,

**Comment by daniel-j-h** [comment]
In the upcoming release you can even decide to avoid tolls and highways at query time:

- https://github.com/Project-OSRM/osrm-backend/pull/4315
- https://github.com/Project-OSRM/osrm-backend/issues/4006

you have to compile from master or wait a week or so until we have a new release.

**Comment by RSA77** [comment]
Thanks Daniel for your quick reply.
With OSRM 5.3.0 (I don't know which OSRM-backend corresponds to 5.3.0, to check...), installed at a customer solution, it seems to happen some wierd results when routing with avoiding toll_booth option.
I am still waiting for more information about how they made their tests, but it seems that sometimes OSRM, provide a route that includes the toll_both road, but just before arriving to the barrier, it goes into arroung (either in a close forest, or a trunk road, etc..) just to avoid the barrier. or even they get results where OSRM detects a toll_booth in one direction but not in the other.
I suspect they played with profile file but without setting it correctly. I am waiting for more clarification, but meanwhile, i wonder if any bug was already identified and that could provoke such behavior.

Best Regards,

**Comment by RSA77** [comment]
Hello Daniel,

Do you have any Release number that includes this toll exclusion (See your last post) ? 
It seems that commit 4315 has been done at the 21st of August and the release 5.12 was done 21 days ago, the day you provided your answer to me. So i guess R5.12 includes this commit. 
Could you confirm it's the 5.12 release you mentioned in your last post or shall i wait for a newer one ?

Best Regards,

**Comment by daniel-j-h** [comment]
Yep, 5.12 has `exclude` support see

https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5120

**Comment by RSA77** [comment]
Ok thanks Daniel for your help. 

I will close this topic.
